### PR TITLE
Create LICENSE.txt

### PR DESCRIPTION
**Pull request by mattdrayer**

### CODE REVIEW

**Review by SHGODE — APPROVED** [review]
Approved

**Comment by mattdrayer** [comment]
Still need a second review of this PR

**Comment by mattdrayer** [comment]
@OpenLXP/contributors we need one more review of this PR in order to merge -- @micson-us has provided one.

**Comment by welch-connor** [comment]
duplicate, covered within the 'feature/dau-es-ingest' PR

**Pull request closed without merging**
